services:
  mongo1:
    container_name: mongo1
    image: mongo:6
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "mongoReplSet"
      ]

  mongo2:
    container_name: mongo2
    image: mongo:6
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "mongoReplSet"
      ]
  mongo3:
    container_name: mongo3
    image: mongo:6
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "mongoReplSet"
      ]
  pollBackend:
    container_name: pollBackend
    image: pollbackend
    restart: always
    volumes:
      - ./src/:/app/src
    ports:
      - 8000:8000
